export { default as AllDiseases } from "./AllDiseases"
export { default as CreateDisease } from "./CreateDisease"
export { default as Articles } from "./Articles"
export { default as EditDisease } from "./EditDisease"
export { default as DiseaseBaseLayout } from "./DiseaseBaseLayout"
// export { default as AllSymptoms } from "./Symptoms/AllSymtpoms"
// export { default as CreateSymptom } from ".Symptoms/CreateSymptom"
// export { default as EditSymptom } from "./Symptoms/EditSymptom"